name: docs-deploy 
on:
  push:
    branches: 
      - main
  workflow_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: '0'
      - uses: actions/setup-python@v4
        with:
          python-version: 3.x
      - run: pip install mkdocs-material
      - run: pip install mkdocs-git-revision-date-localized-plugin
      - run: pip install mkdocs-git-authors-plugin
      - run: pip install mkdocs-enumerate-headings-plugin
      - run: pip install mkdocs-glightbox
      - run: pip install mkdocs-print-site-plugin
      - run: mkdocs gh-deploy --force
