name: docs-deploy 
on:
  push:
    branches: 
      - main
#  pull_request:
#    types:
#      - opened
#      - reopened
  workflow_dispatch:
concurrency:
  group: "docs"
  cancel-in-progress: true
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: '0'
      - uses: actions/setup-python@v5
        with:
          python-version: 3.x
      - run: pip install mkdocs-material
      - run: pip install mkdocs-git-revision-date-localized-plugin
      - run: pip install mkdocs-git-authors-plugin
      - run: pip install mkdocs-enumerate-headings-plugin
      - run: pip install mkdocs-glightbox
      #- run: pip install mkdocs-print-site-plugin
      - run: mkdocs gh-deploy --force
